#!/bin/bash

set -euo pipefail

SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")

if [ $# -ne 1 ] ; then
    echo "Usage: $SCRIPT_NAME <dataset1>"
    exit 1
fi


$SCRIPT_DIR/cbq --dataset=$1 - <<'EOF'
select label as `Labels in $DATASET`, count as `Count`, round(percent, 1) as `%`
from $DATASET.summary
order by sort_order;
EOF
